export const PRELOADER_SHOW = 'PRELOADER_SHOW';
export const PRELOADER_HIDE = 'PRELOADER_HIDE';

export const START_REQUEST = 'START_REQUEST';
export const REQUEST_SUCCESSFUL = 'REQUEST_SUCCESSFUL';
export const REQUEST_FAIL = 'REQUEST_FAIL';